export const searchData = [
    {
        "VIN": "missing",
        "car_id": 7301599110,
        "conditions": "good",
        "cylinders": "8 cylinders",
        "description": "2006 GMC Envoy Denali! 4x4, 129,000 miles, runs drives and looks excellent! Super clean body, super clean leather interior, sunroof, instant, non smoker, good tires and brakes! 5.3 tons of power! Super clean sharp suv! Clean title, we are a dealer located just over the Mass / Nh line at 66 ROUTE 125 BRENTWOOD NH, 03833 calls to 603 760 8780 AT THE ASKING PRICE OF 8995 vehicle comes with a 1 year powertrain warranty!",
        "drive": "4wd",
        "fuel": "gas",
        "image_url": "https://images.craigslist.org/00S0S_gZC6i8armkez_0CI0t2_600x450.jpg",
        "lati": "41.797500",
        "longi": "-71.060700",
        "manufacturer": "gmc",
        "model": "envoy denali",
        "odometer": 129000,
        "paint_color": "white",
        "posting_date": "Sun, 04 Apr 2021 07:11:25 GMT",
        "price": "193988.78",
        "region": "rhode island",
        "region_url": "https://providence.craigslist.org",
        "size": "mid-size",
        "state": "ri",
        "title_status": "clean",
        "transmission": "automatic",
        "type": "coupe",
        "url": "https://providence.craigslist.org/ctd/d/assonet-2006-gmc-envoy-denali-53/7301599110.html",
        "year": 2006
    },
    {
        "VIN": "missing",
        "car_id": 7301667054,
        "conditions": "good",
        "cylinders": "8 cylinders",
        "description": "SOLD AS, 2006 GMC Sierra 2500 SLT 137,000 miles LBZ Duramax  Power everything, leather, extended cab, rough country 6 inch lift professional installed, oversized tires and rims, turbo back borla exhaust, stainless steel brake and fuel lines, rubber tranny lines just installed.  Aftermarket stereo with Bluetooth, heated seats, banks cold air intake, FASS lift pump system with CAT filters just replaced and fresh oil change. Frame was oiled by previous owner every year. Powerstop upgraded brake kit all around. Has fisher minute mount 2 plow setup included but in rough shape.  Cons, Needs e brake repaired( I have parts and will include)  Needs rotors and pads all the way around. Needs front differential, I removed old one because it failed. So you will need to have truck towed or trailered if bought. You will be able to start to hear and check truck out but won’t be able to drive.  Text or email 508- seven 89 914 zero Cash or bank check no scammers NO TRADES",
        "drive": "4wd",
        "fuel": "diesel",
        "image_url": "https://images.craigslist.org/00F0F_7DRcK5HgYyfz_0dm09H_600x450.jpg",
        "lati": "42.052100",
        "longi": "-71.848600",
        "manufacturer": "gmc",
        "model": "sierra 2500 lbz duramax",
        "odometer": 137000,
        "paint_color": "brown",
        "posting_date": "Sun, 04 Apr 2021 11:35:05 GMT",
        "price": "27910.35",
        "region": "worcester / central MA",
        "region_url": "https://worcester.craigslist.org",
        "size": "full-size",
        "state": "ma",
        "title_status": "clean",
        "transmission": "automatic",
        "type": "truck",
        "url": "https://worcester.craigslist.org/cto/d/webster-2006-gmc-sierra-2500-duramax-lbz/7301667054.html",
        "year": 2006
    },
    {
        "VIN": "missing",
        "car_id": 7302696124,
        "conditions": "good",
        "cylinders": "8 cylinders",
        "description": "2005 GMC 2500 for parts , 6.0 motor 176,000 miles runs and drives good , 4x4 $2900.00",
        "drive": "fwd",
        "fuel": "gas",
        "image_url": "https://images.craigslist.org/00w0w_a5yj0b6WiHaz_0t20CI_600x450.jpg",
        "lati": "41.781500",
        "longi": "-71.718700",
        "manufacturer": "gmc",
        "model": "2500",
        "odometer": 276178,
        "paint_color": "white",
        "posting_date": "Tue, 06 Apr 2021 13:42:54 GMT",
        "price": "193988.78",
        "region": "rhode island",
        "region_url": "https://providence.craigslist.org",
        "size": "mid-size",
        "state": "ri",
        "title_status": "parts only",
        "transmission": "automatic",
        "type": "coupe",
        "url": "https://providence.craigslist.org/cto/d/foster-2005-gmc-2500/7302696124.html",
        "year": 2005
    },
    {
        "VIN": "1GTR8CED6KZ374754",
        "car_id": 7303130831,
        "conditions": "good",
        "cylinders": "8 cylinders",
        "description": "Carvana is the safer way to buy a car During these uncertain times, Carvana is dedicated to ensuring safety for all of our customers. In addition to our 100% online shopping and selling experience that allows all customers to buy and trade their cars without ever leaving the safety of their house, we’re providing touchless delivery that make all aspects of our process even safer. Now, you can get the car you want, and trade in your old one, while avoiding person-to-person contact with our friendly advocates. There are some things that can’t be put off. And if buying a car is one of them, know that we’re doing everything we can to keep you keep moving while continuing to put your health safety, and happiness first. Vehicle Stock# 2000841611📱 Want to instantly check this car’s availability? Call us at  401-300-5707Just text that stock number to 855-976-4304 or head to  and plug it into the search bar!Get PRE-QUALIFIED for your auto loan in 2 minutes - no hit to your credit:http://finance.carvanaauto.com/6554627-74675Looking for more cars like this one? We have 17 GMC Sierra 1500 Double Cab in stock for as low as $23990!Why buy with Carvana? We have one standard: the highest. Take a look at just some of the qualifications all of our cars must meet before we list them.150-POINT INSPECTION: We put each vehicle through a 150-point inspection so that you can be 100% confident in its quality and safety. See everything that goes into our inspections at:NO REPORTED ACCIDENTS: We do not sell cars that have been in a reported accident or have a frame or structural damage.7 DAY TEST OWN MONEY BACK GUARANTEE: Every Carvana car comes with a 7-day money-back guarantee. Why? It takes more than 15-minutes to make a decision on your next car. Learn more about test owning at http://about.carvanaauto.comFLEXIBLE FINANCING, TRADE INS WELCOME: We’re all about real-time financing without the middle man. Need financing? Pick a combination of down and monthly payments that work for you. Have a trade-in? We’ll give you a value in 2 minutes. Check out everything about our financing at:http://finance.carvanaauto.com/6554627-74675COST SAVINGS: Carvana's business model has fewer expenses and no bloated fees compared to your local dealership. See how much we can save you at http://about.carvanaauto.comPREMIUM DETAIL: We go the extra mile so that your car is looking as good as new. There are a lot of specifics that we won’t list here (we wash, clean, buff, paint, polish, wax, seal), but trust us that when your car arrives, it’s going to look sweet.Vehicle Info for Stock# 2000841611Trim: Elevation Pickup 4D 6 1/2 ft pickupMileage: 7k milesExterior Color: BlackInterior Color: GRAYEngine: EcoTec3 5.3L V8 355hp 383ft. lbs.Drive: Two Wheel DriveTransmission: Automatic, 8-Spd w/OverdriveVIN: 1GTR8CED6KZ374754Dealer Disclosure: Price excludes tax, title, and registration (which we handle for you).Disclaimer: You agree that by providing your phone number, Carvana, or Carvana’s authorized representatives*, may call and/or send text messages (including by using equipment to automatically dial telephone numbers) about your interest in a purchase, for marketing/sales purposes, or for any other servicing or informational purpose related to your account. You do not have to consent to receiving calls or texts to purchase from Carvana. While every reasonable effort is made to ensure the accuracy of the information for this GMC Sierra 1500 Double Cab, we are not responsible for any errors or omissions contained in this ad. Please verify any information in question with Carvana at 401-300-5707*Including, but not limited to, Bridgecrest Credit Company, GO Financial and SilverRock Automotive.*GMC* *Sierra* *1500* *Double* *Cab* *Base* *GMC* *Sierra* *1500* *Double* *Cab* *SLE* *GMC* *Sierra* *1500* *Double* *Cab* *SLT* *GMC* *Sierra* *1500* *Double* *Cab* *Denali* *GMC* *Sierra* *1500* *Double* *Cab* *Work* *Truck* *4x2* *GMC* *Sierra* *1500* *Double* *Cab* *4x4* *Crew* *Cab* *GMC* *Sierra* *1500* *Double* *Cab* *Regular* *Cab* *Extended* *Cab* *Truck* 2022  2021  2020  2019  2018  2017  2016  2015  2014  2013  2012  2011  2010  2009  2008  2007  2006  2005  2004  2003  2002  2001  2000   22  21    19  18  17  16  15  14  13  12  11  10  09  08  07  06  05  04  03  02  01  00",
        "drive": "fwd",
        "fuel": "gas",
        "image_url": "https://images.craigslist.org/00N0N_1vaGnrfi1wbz_0gw0co_600x450.jpg",
        "lati": "41.820000",
        "longi": "-71.410000",
        "manufacturer": "gmc",
        "model": "sierra 1500 double cab",
        "odometer": 7256,
        "paint_color": "black",
        "posting_date": "Wed, 07 Apr 2021 11:31:12 GMT",
        "price": "180874.67",
        "region": "rhode island",
        "region_url": "https://providence.craigslist.org",
        "size": "mid-size",
        "state": "ri",
        "title_status": "clean",
        "transmission": "other",
        "type": "pickup",
        "url": "https://providence.craigslist.org/ctd/d/providence-2019-gmc-sierra-1500-double/7303130831.html",
        "year": 2019
    },
    {
        "VIN": "7GZ37SCG8KN004979",
        "car_id": 7303200797,
        "conditions": "excellent",
        "cylinders": "8 cylinders",
        "description": "Low miles! Clean inside and out! Financing available.",
        "drive": "rwd",
        "fuel": "gas",
        "image_url": "https://images.craigslist.org/00909_fMcEup0T3Slz_0CI0t2_600x450.jpg",
        "lati": "42.096700",
        "longi": "-71.549900",
        "manufacturer": "gmc",
        "model": "savana box truck",
        "odometer": 6955,
        "paint_color": "white",
        "posting_date": "Wed, 07 Apr 2021 13:17:20 GMT",
        "price": "27910.35",
        "region": "worcester / central MA",
        "region_url": "https://worcester.craigslist.org",
        "size": "full-size",
        "state": "ma",
        "title_status": "clean",
        "transmission": "automatic",
        "type": "truck",
        "url": "https://worcester.craigslist.org/cto/d/mendon-gmc-2019-box-truck/7303200797.html",
        "year": 2019
    },
    {
        "VIN": "missing",
        "car_id": 7303338323,
        "conditions": "good",
        "cylinders": "8 cylinders",
        "description": "Runs fine just needs an oil change. Has Aftermarket fuel pump.",
        "drive": "4wd",
        "fuel": "gas",
        "image_url": "https://images.craigslist.org/00A0A_bDxGUdWedVGz_0c60bD_600x450.jpg",
        "lati": "41.784500",
        "longi": "-71.395900",
        "manufacturer": "gmc",
        "model": "yukon denali",
        "odometer": 278000,
        "paint_color": "brown",
        "posting_date": "Wed, 07 Apr 2021 16:59:45 GMT",
        "price": "45660.33",
        "region": "rhode island",
        "region_url": "https://providence.craigslist.org",
        "size": "full-size",
        "state": "ri",
        "title_status": "missing",
        "transmission": "automatic",
        "type": "SUV",
        "url": "https://providence.craigslist.org/cto/d/providence-gmc-yukon-denali-sport/7303338323.html",
        "year": 2001
    },
    {
        "VIN": "missing",
        "car_id": 7303342334,
        "conditions": "good",
        "cylinders": "6 cylinders",
        "description": "1-OWNER CLEAN CARFAX NEW CAR TRADE IN AT CHEVY DEALER ABSOLUTELY GORGEOUS VEHICLE RUNS EXCELLENT NEEDS NOTHING NO RUST 106,000 MILES FACTORY NAVIGATION HEATED SEATS SUNROOF ALL POWER SATELLITE RADIO ONSTAR 6CYL 4WD GREAT ON GAS EVERYTHING WORKS NO DAMAGE TO VEHICLE VERY COMFORTABLE $13990.00",
        "drive": "4wd",
        "fuel": "gas",
        "image_url": "https://images.craigslist.org/00101_6JaT7sfkIF2z_0CI0t2_600x450.jpg",
        "lati": "42.318200",
        "longi": "-71.646400",
        "manufacturer": "gmc",
        "model": "terrain denali",
        "odometer": 106000,
        "paint_color": "grey",
        "posting_date": "Wed, 07 Apr 2021 17:06:05 GMT",
        "price": "45660.33",
        "region": "worcester / central MA",
        "region_url": "https://worcester.craigslist.org",
        "size": "mid-size",
        "state": "ma",
        "title_status": "clean",
        "transmission": "automatic",
        "type": "SUV",
        "url": "https://worcester.craigslist.org/ctd/d/northborough-2013-gmc-terrain-denali/7303342334.html",
        "year": 2013
    },
    {
        "VIN": "1GKKVRED9CJ321547",
        "car_id": 7303527042,
        "conditions": "good",
        "cylinders": "6 cylinders",
        "description": "This  AWD SUV runs and drives great. We  serviced this vehicle oil and filter, replaced the rear brake pads and rotors, checked,  belts hoses, front end all fluids ETC. and  installed a new muffler.",
        "drive": "4wd",
        "fuel": "gas",
        "image_url": "https://images.craigslist.org/00J0J_l5GWADbEoaEz_0CI0t2_600x450.jpg",
        "lati": "42.101245",
        "longi": "-71.704538",
        "manufacturer": "gmc",
        "model": "acadia",
        "odometer": 103125,
        "paint_color": "silver",
        "posting_date": "Thu, 08 Apr 2021 04:22:25 GMT",
        "price": "45660.33",
        "region": "worcester / central MA",
        "region_url": "https://worcester.craigslist.org",
        "size": "full-size",
        "state": "ma",
        "title_status": "clean",
        "transmission": "automatic",
        "type": "SUV",
        "url": "https://worcester.craigslist.org/ctd/d/manchaug-2012-gmc-acadia-slt-awd/7303527042.html",
        "year": 2012
    },
    {
        "VIN": "2GKFLVEK1E6137184",
        "car_id": 7303548131,
        "conditions": "good",
        "cylinders": "6 cylinders",
        "description": "Why Buy From Imperial Chrysler Dodge Jeep RAM?Whether it is a new Ford, Chevrolet, Toyota, Chrysler, Dodge Jeep, RAM or Hyundai, our many different brands have what you're looking for. Each brand has its own individual showroom here on our campus, and you can stop in to all of them to browse our selection of vehicles, and take test drives in vehicles until you've found something that fits your needs. There is sure to be something for you, as combined, our dealerships have over 2,000 new and used cars available for you. Stock# 41714A508-928-5068 - Call now for your best deal!For all details on this vehicle, visit:http://vdp.gatehouseauto.com/6926976-76312 Vehicle OverviewTrim: SLE suv Mileage: 90k miles Exterior Color: Black Interior Color: Light Titanium Engine: Gas/Ethanol I4 2.4L/145 Drive: awd Transmission: Automatic VIN:  2GKFLVEK1E6137184Seller Comments:  To request a price quote, visit:http://vdp.gatehouseauto.com/6926976-76312 *CALL* or *TEXT* us to see how we can help you finance this GMC Terrain!Mention you saw STOCK #41714A on Craigslist for a great deal: 508-928-5068Standard FeaturesExterior: BumpersFront and rear body-colorExterior: Fog lampsFront roundHalogenExterior: GlassDeep-tinted (all windowsExcept light-tinted glass on windshield and driver- and front passenger-side glass)Exterior: GrilleCharcoal with chrome surroundExterior: HeadlampsHalogen projector lampExterior: LiftgateRear manual with fixed glassExterior: MirrorsOutside heated power-adjustableBody-colorManual-folding and integral spotter mirrorExterior: Spare tire and wheelExterior: Tires Disclaimer: While every reasonable effort is made to ensure the accuracy of the information for this GMC Terrain, we are not responsible for any errors or omissions contained in this ad. Please verify any information in question with Imperial Chrysler Dodge Jeep RAM at 508-928-5068*GMC* *Terrain* *SLE-1* *GMC* *Terrain* *SLE-2* *GMC* *Terrain* *SLT-1* *GMC* *Terrain* *SLT-2* *GMC* *Terrain* *Denali* *Front-Wheel* *Drive* *GMC* *Terrain* *All-Wheel* *Drive* *SUV* 2022  2021  2020  2019  2018  2017  2016  2015  2014  2013  2012  2011  2010  2009  2008  2007  2006  2005  2004  2003  2002  2001  2000   22  21    19  18  17  16  15  14  13  12  11  10  09  08  07  06  05  04  03  02  01  00",
        "drive": "fwd",
        "fuel": "other",
        "image_url": "https://images.craigslist.org/00r0r_1Mko6sWO94bz_0ak07K_600x450.jpg",
        "lati": "42.102661",
        "longi": "-71.562075",
        "manufacturer": "gmc",
        "model": "terrain sle1",
        "odometer": 90332,
        "paint_color": "black",
        "posting_date": "Thu, 08 Apr 2021 07:40:40 GMT",
        "price": "23761.83",
        "region": "worcester / central MA",
        "region_url": "https://worcester.craigslist.org",
        "size": "full-size",
        "state": "ma",
        "title_status": "clean",
        "transmission": "automatic",
        "type": "other",
        "url": "https://worcester.craigslist.org/ctd/d/mendon-2014-gmc-terrain-sle-suv-black/7303548131.html",
        "year": 2014
    },
    {
        "VIN": "missing",
        "car_id": 7303896399,
        "conditions": "good",
        "cylinders": "6 cylinders",
        "description": "Very clean and reliable compact suv, low miles, 6 cylinder, automatic transmission, with all the power options you can think of If interested let know. 774-386-six03five Thanks",
        "drive": "fwd",
        "fuel": "gas",
        "image_url": "https://images.craigslist.org/00D0D_ikrg9gnO4Uoz_0t20CI_600x450.jpg",
        "lati": "42.311000",
        "longi": "-71.795800",
        "manufacturer": "gmc",
        "model": "terrain",
        "odometer": 129000,
        "paint_color": "black",
        "posting_date": "Thu, 08 Apr 2021 18:09:16 GMT",
        "price": "45660.33",
        "region": "worcester / central MA",
        "region_url": "https://worcester.craigslist.org",
        "size": "full-size",
        "state": "ma",
        "title_status": "clean",
        "transmission": "automatic",
        "type": "SUV",
        "url": "https://worcester.craigslist.org/cto/d/worcester-gmc-terrain-slt/7303896399.html",
        "year": 2010
    }
]